### ISSUE TITLE
What we got vs what we give

### ISSUE THREAD

**Issue by JayNasty** [jeffw16/unt-grade-distributions#15]
Theres a difference in what UNT gave us intially and what we converted.
example: spring2019.csv data is not the same results within complete.json(where we search and put together the end results). I noticed this with barber for cal 1 MATH 1710. Compare the grades given with the complete.json we output with and it's wrong. I assume the site is dying anyway due to everyone having other projects to work on.

The answer for fixing this moving forward? Maybe skip converting from excel to json and just query csv files directly. the csv files seem more accurate in terms of overall grades given. Take care guys~

**Comment by jeffw16** [comment]
This is a known issue with the dataset. The UNT System General Counsel refuses to be cooperative with our open records requests. We have filed complaints with the Texas Attorney General's office to no avail. There is not much of a chance of getting new records after our last few attempts went south.
